apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: taa-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:kumcp/yaml.git
    targetRevision: master
    path: .
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: default


  syncPolicy:
    automated:
      prune: false
      selfHeal: false
      allowEmpty: false
    syncOptions:
    - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m